name: Firebase Deploy

on:
  push:
    branches:
      - main # main ブランチにプッシュされたときにデプロイ

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Firebase login
        run: firebase login --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Firebase deploy
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
